# Generated by Django 5.2 on 2025-04-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('external_campaign_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.client')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('external_ad_id', models.CharField(max_length=255)),
                ('ad_name', models.CharField(max_length=255)),
                ('ad_status', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.client')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.datasource')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='processor.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('external_lead_id', models.CharField(max_length=255)),
                ('lead_data', models.JSONField()),
                ('received_at', models.DateTimeField()),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.ad')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.client')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('conversions', models.BigIntegerField(default=0)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.ad')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.client')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.datasource')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['client', 'datasource', 'external_campaign_id'], name='processor_c_client__1d4e98_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['client', 'datasource', 'external_ad_id'], name='processor_a_client__2277b6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'datasource', 'external_lead_id'], name='processor_l_client__bd46c7_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['client', 'datasource', 'date'], name='processor_p_client__cf1dcd_idx'),
        ),
    ]
