# Generated by Django 5.2 on 2025-04-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('api_base_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('none', 'None')], max_length=50)),
            ],
            options={
                'unique_together': {('name', 'api_base_url')},
            },
        ),
        migrations.CreateModel(
            name='ClientDataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('auth_credentials', models.JSONField()),
                ('fetch_config', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.client')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.datasource')),
            ],
            options={
                'unique_together': {('client', 'datasource')},
            },
        ),
    ]
